# Generated by Django 4.2.11 on 2024-03-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_name', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(default='HAmfGiaVUy9nKPaZTX4gqTIDLHVzLJRmsBodYuRLxUnU0HFxXj8nzVVUNesIiwia5prgwBDiJzIeM6UyFNx7XHTtL0RPOFfUrkAXTQrd8QWnWkigcP3yFDXzPBeM8x9IqCKZR5OEvkntLE7YQxno6rerV30QmKeAeySWk6lZtowi8mogVdb52hra9zGMFI9i4fYNhdIM', max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('bg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg', to='bg_review.boardgame')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bg_review.review')),
                ('visitor', models.ForeignKey(default='o3yMomLsSKjFRl3TR3PxhDazvfqTlWDQYZZ4D9HeIJJGg9aqub7Dnxj3LZQWQiDHGkqJGgLm6f52AcKTTn7nnMNHUiUqJ6TBsxeWw4qtTRiAlVLRT2OhufnFkZTb9DktcZ0r4Krp8cEo6TPBWZZ2ssWXn8OBKU8wWUCIhcDri4lmoBXhRRl8Dl4EsY7s8IHKp9bDslVH', on_delete=django.db.models.deletion.RESTRICT, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='bg_review.review')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('guest', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='bg_review.review')),
            ],
        ),
    ]
