# Generated by Django 4.2.11 on 2024-03-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='wSY1JTgyUvsW1yZ51lxW7dgbHBKsPluxSREz4tHUhZVYZov4Zu22IwumUhQGiLFG3rzfMDiXEnJnyY4EUC1vHli7npPtIrxHvU2AsBIyp3IRfyy7qAMnEMfH5OlQ7B1VwnBao9WCuYkKqdkIGsZBK3Lg22ueopjlW1mm0b8LVr3jelyvk62lfw0T8mn0L7I9DMkUDHyP', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
