# Generated by Django 4.2.11 on 2024-03-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='visitor',
            field=models.ForeignKey(default='fkQ5Q2PiMr321ucGrd5JpJKZO6PPDaPniISLMPompjmdBeOn31EHg7I1yFcDxXKseQBzTkrR1blNf6B7OVv7F2UmjpBv5lsBEK1HzVaLtdLGXYbef3KUBHrUtoesRmZeri3TfoqBmTfEMovZpnuo3xVZiI7x0s6pQS3qjnkgyv70ZYNTKTNRC2XaYTOIjR4uA6pUGBkL', on_delete=django.db.models.deletion.RESTRICT, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='f7c8smCVg7oRKWno2du2tZH8IA3vI5NkaKvADBZiZFLr42t9GJrERQX2040V7a8tadMuEoPrHUHHkwfqHKaVDIcx6kCnVt9SNPZfsBq0WYt6Uks1T7qPiOyv7wiTcpWXcU1HL2ncYueSfmofXPuBkFsMJOKiShTROOOOShsUNzUPLgCrHPRtWTvKp1I5zUOTquoRxq9R', max_length=200, unique=True),
        ),
    ]
