# Generated by Django 4.2.11 on 2024-03-28 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg_review', '0002_alter_rating_visitor_alter_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='visitor',
            field=models.ForeignKey(default='VvWN1QGAtu02y4E5Ee7q8048V5JmJvimQzmPWW3xPcEhjCVg6R2FyDAcpoAhMpUfNopa6nRg9W4DbRGX8m8CAbK8GZ6l5XQkTLqZ9oWxbhrKzbGAPWbXc3aVkixsfDVtCq9JXPz82ErMGnfRbd98xhSBr2LYyVjNibRJVss7d4Vr0TtVLPrBWc04n7QJKAOdt7VUDRA9', on_delete=django.db.models.deletion.RESTRICT, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='gr5y5K0PadSjhMrLU7g2vqjnW8EoRc1SRgUXeG3iPvrATxfL6Su7jq2kbBthbCAUHEloRO8eRVJN4HnW0d1e4tJlQa3DkUMUNYA62MosQj992SEEEgQzXRPmbwPadZKn4pcDsIg0zNIAey9SPDsHKY9InEMPjcvMszEGM1P3r9RjC4NMtq7zMxWA19k25xiluigslWo0', max_length=200, unique=True),
        ),
    ]
