# Generated by Django 4.2.11 on 2024-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_review', '0002_review_slug_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='WO4jpxIJxJufEk0FIZZdLzDJ0uufmZb9SAWEjCNA3xpk9xEr6u1qqtOVHdMUUip2dKuCDHZjvQ2M22EzNb5jEVttU2Q6fiCnTlJdiKbMozfpb5i8qFqRZNdIr8dqvYxQ4karvnmNjFfOethofehlHLOf3UdZO8CgWIEL7i3ZGHghTgsVY47NTgOyobABNtDexpTcA2IX', max_length=200, unique=True),
        ),
    ]
