# Generated by Django 4.2.11 on 2024-03-29 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg_review', '0003_rating_rating_alter_rating_visitor_alter_review_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['created_on', 'approved']},
        ),
        migrations.AlterModelOptions(
            name='commentguest',
            options={'ordering': ['created_on', 'approved']},
        ),
        migrations.AlterModelOptions(
            name='commentuser',
            options={'ordering': ['created_on', 'approved']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on', 'approved']},
        ),
        migrations.AddField(
            model_name='boardgame',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='visitor',
            field=models.ForeignKey(default='gqOPdvUrSumKoKc2LCSjVP6LaCutKcX2n6fASQoPbhnucgT8SiK3gWqQEL6xegt1FwWUXoMCUGIEbwIO2ToYNziZZR0KruXKkLiJQE90DGMwHv8Gl03Ofq85eoZUcVWIe3VOUI93UGK4bFDpzHPQRNkg9oVRwGjzqGYNPqx2J87vZO73TtiGv9EFiiyJ1z9EXijiCDQY', on_delete=django.db.models.deletion.RESTRICT, related_name='visitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='c1VC2QsYT6bbeDdIMKwsGqzJMVpCvw5VgFOJLDycw5DUg8dW10IfuV8HmgDFf6hGA63WRIRmjWvkm8Mht20gcCRmj31JBo5fj4lxPvNMYZoR3tvHGmOpH4dOiBcvqK4zCbI90zmPwD3fo6oBZCwKYyDsf5svetfCvFt3EYTNI46hrG26PmPFgAIzOjooFfKOcO1zNyTW', max_length=200, unique=True),
        ),
    ]
